### ISSUE TITLE
AC without integrated temperature sensor.

### ISSUE THREAD

**Issue by RichardTHF** [Elethom/homebridge-gree-heatercooler-v2#1]
Firstly, absolutely fantastic integreation into HomeBridge. 

I have found a small issue that shows it's head on device, but not on the web controls. 

If the AC you are using doesn't have a built in temperature sensor (i.e. KFR-50G(50582)FNCa-A2 and KFR-26G(26592)FNhAa-A1) it will not turn on or off via the Apple Home app. 

Would it be possible to integrate a option similar to the /homebridge-gree-heatercooler project that allows you to use the target temp as the current temperature. 

```
        {
            "accessory": "GreeHeaterCooler",
            "address": "10.XXX.XXX.XXX",
            "model": "KFR-26G(26592)FNhAa-A1(WIFI)",
            "name": "Study AC",
            "serialNumber": "4J3098XXXXXX",
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "useTargetTempAsCurrent": true,
            "updateInterval": 1000,
            "retryInterval": 5000
        }
```

**Comment by Elethom** [comment]
I’ll look into it no problem. But be noted, with this option on it will not be able to determine whether it’s actively working or being idle.

**Comment by Elethom** [comment]
Hi, please checkout version 0.1.1. Hope this solves your problem. I couldn't test it without knowing how an actual device would respond to invalid status requests. Please come back with logs and screenshots if you encounter any further issues.

**Comment by RichardTHF** [comment]
Ok, so it worked but only on a single device. 

When i had three units setup, only the last unit was the only one that would actually work. 

![image](https://user-images.githubusercontent.com/5789676/104146104-7a191a80-5404-11eb-9599-3bb043921353.png)

They all work via the web interface.

![image](https://user-images.githubusercontent.com/5789676/104146148-a9c82280-5404-11eb-9c24-8aa9564d6fc4.png)

There is nothing in the dashboard logs, where else should I look?

**Comment by Elethom** [comment]
Turn on debug mode and you’ll see the logs. 👀

**Comment by RichardTHF** [comment]
So, I don't think it is the change that you made causing the issue, I believe that it is just having multiple devices. If i change the order that the devices appear in the configuration file it will only ever work with the last device... 


https://richardjdavies.com/paste/?a07bec628bf6705d#4MPB4MrYkv8PT59YcF1S3p93m789FQHbhXgN1bB2kvVX

**Comment by Elethom** [comment]
Ah, found the issue. Just me being stupid. 😅

Published 0.1.2, shoulda fixed the issue. Can you try it?

**Comment by RichardTHF** [comment]
hahaha, not stupid at all! 

Ok, so it now works on two out of three of the devices. 

The first one in the list is still not working in the Apple Home app.

**Comment by RichardTHF** [comment]
![image](https://user-images.githubusercontent.com/5789676/104159642-ac3d7300-542a-11eb-8435-2dfd775716aa.png)
Still seen as undefined.

**Comment by Elethom** [comment]
What if there is only Study AC? Is it broken on that case, too?

**Comment by RichardTHF** [comment]
Nope, if it is on it's own it works perfectly.

![image](https://user-images.githubusercontent.com/5789676/104160098-82d11700-542b-11eb-8cb3-907a10b3c0cf.png)

**Comment by RichardTHF** [comment]
Weirdly, changing the order has fixed it...only thing I have changed in the config file is the order and it seems to now work perfectly. 

Thank you for all the help :)

**Comment by solbadguy2010** [comment]
Hi, i have the same error. My Gree AC is shown as offline in the Home App.

here are the outputs of the Debug log:

`[12/01/2021, 12:32:50] [GreeHeaterCooler] Config loaded: {
  "accessory": "GreeHeaterCooler",
  "name": "GreeHeaterCooler",
  "host": "10.0.1.84",
  "model": "GWH24QD",
  "serialNumber": "4M33600000330",
  "minimumTargetTemperature": 18,
  "maximumTargetTemperature": 25,
  "fakeSensor": true,
  "updateInterval": 1000,
  "retryInterval": 5000
}
[12/01/2021, 12:32:50] [GreeHeaterCooler] Setup socket

...

12/01/2021, 12:32:50] [GreeHeaterCooler] Socket setup at 39320
[12/01/2021, 12:32:50] [GreeHeaterCooler] Scan for device at undefined:7000

...

[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: currentTemperature
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: targetState
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: units
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: targetTemperature
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: currentState
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: active
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: targetTemperature
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: swingMode
[12/01/2021, 12:32:57] [GreeHeaterCooler] [undefined] Get characteristic: speed
`

Any idea whats wrong here? The old Greeheatercooler plugin is working fine.

Thank you!
