### ISSUE TITLE
Plugin not able to control AC after some time

### ISSUE THREAD

**Issue by solbadguy2010** [Elethom/homebridge-gree-heatercooler-v2#11]
Hi,
i have another strange behavior. When i reboot my homebridge the Plugin shows "Device not found" some times, then it bounds to the device. I am able to speed up this process by disabling and reenabling Wifi on the AC with the remote.

I then perfectly able to control my AC. After some hours the AC stops to repsond to Homekit/Homebridge commands.

I can only make the AC responsible again by re-booting Homebridge or by disabling and reenabling Wifi on the AC with the remote. It "feels" like the "bounding" gets lost after some time. While all of this is happening there is not entry in the log of your plugin. No "bounding lost", no "rebound to device", nothing.

Any ideas? Can i help you with testing something?

**Comment by Elethom** [comment]
It would help if you can paste the logs here when it says "Device not found" and right before it loses connection.

**Comment by solbadguy2010** [comment]
You can see it in my old issue here:

https://github.com/Elethom/homebridge-gree-heatercooler-v2/issues/10

but there is no log entry when loosing the connection. I don‘t even know how long it‘s till the connection is lost.

**Comment by Elethom** [comment]
`f4911ed74c27` is only for demonstration. Please remove it or replace it with your own mac if you need it.

**Comment by solbadguy2010** [comment]
No, „ f4911e504354“ is your demo mac. „ f4911ed74c27“ is the correct mac of my AC.

![45A4BA57-41A3-4429-8EEE-E85BDEF69581](https://user-images.githubusercontent.com/30244171/112031849-1154c980-8b3c-11eb-8c77-8602198df77d.png)
