### ISSUE TITLE
Plugin not able to control AC after some time

### ISSUE THREAD

**Issue by solbadguy2010** [Elethom/homebridge-gree-heatercooler-v2#13]
No, „ f4911e504354“ is your demo mac. „f4911ed74c27“ is the correct mac of my AC.

![45A4BA57-41A3-4429-8EEE-E85BDEF69581](https://user-images.githubusercontent.com/30244171/112031849-1154c980-8b3c-11eb-8c77-8602198df77d.png)

_Originally posted by @solbadguy2010 in https://github.com/Elethom/homebridge-gree-heatercooler-v2/issues/11#issuecomment-804251474_

**Comment by Elethom** [comment]
Sorry for the inconvenience. May I ask if you are something like Raspberry Pi?

Please try 0.4.4.

**Comment by solbadguy2010** [comment]
Yes, its a Pi3

**Comment by Elethom** [comment]
@solbadguy2010 
Hi! Please close this issue if the problem doesn't show up anymore. Thanks!

**Comment by solbadguy2010** [comment]
Just tested. HB Service is running since 6  days. AC is not responding to Home App anymore. Issue persists.

**Comment by Elethom** [comment]
@solbadguy2010 
That's weird. No one else has reported the same issue.
Can you please check your network connection? Did your device close connections to save energy or something?

**Comment by Elethom** [comment]
If you don't mind, you can send your `homebridge.log` file here for analysis.

**Comment by Elethom** [comment]
Please check:
https://github.com/homebridge/homebridge/issues/476

**Comment by solbadguy2010** [comment]
Network is fine. Homebridge also. I have 8 other Plugins running fine.
Interesting: just tested again and it worked. No reboot or disabling Wifi this time.
Yes, i also believe that this is some device sleep stuff, but i think it could be the ac.

I will upload the log in a few minutes from my PC, but i haven‘t seen any entries that could help. Does your plugin log more details in Debug Mode?

**Comment by Elethom** [comment]
Yes it does.

I suggest you monitor Wi-Fi connection for AC on your router. Gree uses UDP connection, which means when the it fails on their end, it doesn't come back with an error, it just returns nothing.

**Comment by solbadguy2010** [comment]
Ok. I enabled detailed Wifi logging in the Router and Debug Mode in Homebrige. I will try to see the error happening the next days.

**Comment by Elethom** [comment]
Hello, if there is no further updates regarding this issue, I will close it in 2 days.

**Comment by solbadguy2010** [comment]
Sorry, wasnt able to experience the problem live until now. i contact again if i find something.
