### ISSUE TITLE
Possible Enhancements

### ISSUE THREAD

**Issue by keness521** [Elethom/homebridge-gree-heatercooler-v2#14]
Just received my shipment of 32 WiFi kits for all my units, and have been installing and setting them up and everything is going extremely smoothly!

A couple of possible rainy-day enhancements have come to mind for consideration...

1) X-Fan- Gree units almost all (?) have a X-Fan feature, which keeps the fan blowing a little extra in COOL and DRY modes to dry off the coils. There is no way to utilize this in HomeKit directly. Perhaps this can be a config option? Something like ("xFan": true) in the accessory settings. Then, if sending a command and mode is either COOL or DRY, also send X-Fan true... The "Gree Remote" command for this feature is called "Blo".

2) Light- Similarly, most Gree units can turn their display on and off. Also similarly, there is no way to do this in HomeKit. Perhaps a config option for this would be usable, too. (Unfortunately, there'd be no way to easily turn it back on without using the remote, unless the plug in exposed in addition to a thermostat, also a "switch" accessory corresponding to. Perhaps the config option could be whether or not to expose a "switch" to control the light or not, rather than turning the light on or off itself. The Gree Remote command for this is "Lig".

3) The last one I thought of, and this one is a little bit of a kludge due to HomeKit's lack of support for proper oscillation modes, would be to have config options for them, to basically "hardwire" them. In cool mode, I like the air to blow up a little, because the cool air then slowly "falls" down. Similarly, in heat mode, I like the air to blow low, because heat then rises. Perhaps there could be two config options for the oscillation, one for COOL mode and one for HEAT mode, and we could define which of the Gree Swing Modes we prefer for each mode. The Gree Remote command for this is "SwUpDn", and there are 11 different options. Or, Auto + 10 options.

Just some thoughts about ways maybe some more of the built-in Gree functionality could be incorporated, even though HomeKit doesn't allow it. In many cases, these aren't things I would want to change, so if I could set them in the device's config, that'd be fine.

Thanks for all the hard work!

**Comment by Elethom** [comment]
You're welcome!

These are some good proposals. 1 & 2 implemented in version 0.5.0. I'll look into 3 sometime later for best solutions.

**Comment by keness521** [comment]
Beautifully implemented! Both features are perfect.

**Comment by Elethom** [comment]
3 implemented in 0.6.0.
