### ISSUE TITLE
Fan Mode

### ISSUE THREAD

**Issue by keness521** [Elethom/homebridge-gree-heatercooler-v2#15]
The improvements and enhancements over the last few weeks have been incredible! I almost hate to mention anything else because it seems unappreciative... haha But as I continue setting up a 32-unit system, I've come up with a couple more ideas I thought I would throw out there.

HomeKit lacks a real way to deal with FAN mode on Gree units... HEAT and COOL work great, of course, as far as I understand, there is no real way to use FAN mode.

I'm finding that I really like to set FAN mode any time I'm not actually using the AC. Overnight in the office, for example. It uses almost no electricity, but keeps the air in the space so well circulated.

I can set fan mode on the remote, but there is no way to set it through HomeKit and therefore no way to have scenes or automations use it.

How do you think might be the best way to implement FAN mode? A separate switch like you did for the LIGHT? That would give the option of having the fan mode switch together with the thermostat, or as a separate tile. In FAN mode the set temperature is meaningless, so it doesn't need to be adjusted. I think the regular fan speed control would work for FAN mode as well, right? So the FAN mode switch would just send the fan mode signal, instead of the COOL or HEAT or AUTO or OFF which can be done through the regular thermostat. It is gree-remote "Mod" #3, 'fan'.

**Comment by Elethom** [comment]
Emm... Good idea. I'll look into that later.

**Comment by keness521** [comment]
Awesome! You're really putting a lot of thought and effort into this plug in, and it is much appreciated! I'm pretty certain it is the most stable and well-featured implementation for Gree on _any_ platform at this point!

I just installed 0.6 with the oscillation options, too, and it is working perfectly!

For the FAN mode enhancement, on HomeKit's thermostat color circle dial, at the bottom is the selector for AUTO, HEAT, COOL, and OFF... Those four options are defined and locked by HomeKit, right? You can't add one to have AUTO, HEAT, COOL, FAN and OFF?

If you can add FAN to the list, that is probably the best way to implement FAN mode I would think. If you can't add anything o that like, maybe the switch (like LIGHT) is the best solution...?

Right now, when I put it into FAN mode with the remote, or with the GREE+ app, the Homekit thermostat continues to show COOL or HEAT (whatever it was before I started FAN mode) and the set temperature also still shows the set temperature it was before, too. But even if the actual temperature is much lower or higher, the AC compressor outside will never kick on. And the "blue, green, orange" status indicator in HomeKit stays green (idle) all the time. This all seems perfectly correct, since the set temperature is unimportant in fan mode.

It would be wonderful if there were a clearer way to indicate FAN mode, but I think that may be a HomeKit limitation?

For autoOscillation, which you just implemented, maybe it would be good to include "fan" there as well, even though FAN mode might be activated by switch rather than the HomeKit thermostat dial. At least the oscillation options will all be in one place.

Something like:

      "autoOscillation": {
        "cool": {
          "horizontal": "default",
          "vertical": "fixedHighest"
        },
        "heat": {
          "horizontal": "default",
          "vertical": "fixedLowest"
        },
        "fan": {
          "horizontal": "default",
          "vertical": "full"
        }
      }

**Comment by keness521** [comment]
Actually, the new changes to AUTO mode in v0.6 kind of made FAN mode (the way it displays in HomeKit) a little weird.

Previously, if in FAN mode on the remote, or GREE+ app, you could set a temp, but it didn't really mean anything. It would show the temp as target temp on the unit display and in HomeKit, but again, it didn't mean anything because the fan was just running and that's all.

In HomeKit, in the plugin v0.5 and earlier, it would show the status as GREEN (idle) no matter what the target temperature and room temperature was. This is fine, because it really is idle, it's just blowing the fan, the actual AC isn't running either HEAT or COOL.

In the plugin v0.6, it now displays the unit in AUTO mode if it was set to FAN mode on the remote or GREE+, and it shows the target temperature (even though it is meaningless) as, for example 64-64, instead of just 64.

But worse, it changes the status to orange or blue, depending on the temperature of the room and the target temperature... For fan mode, the status should always be green and nothing else.

I don't know if the plugin would actually try to change the AC mode to HEAT or COOL (since that is the purpose of AUTO mode) but if it does, that would definitely be bad. It would cause the unit to exit FAN mode. In my case, where I have 4 zones per system, it would cause a mode conflict error on the unit if one has exited FAN mode and now is in HEAT mode, for example. FAN isn't compatible with HEAT or COOL on the same system at the same time. They all have to be either FAN or OFF.

Of course, this is all because HomeKit doesn't have the option for fan mode, just AUTO, HEAT and COOL. (And OFF.) Hopefully when you have a moment to look into the FAN mode setting, there is maybe a less confusing way to represent it?

The old v0.5 way was pretty good. Not ideal, but it was probably the best HomeKit can do. (Always green & never says 'Heating to' or 'Cooling to' because it isn't. It did say 'Heat to' or 'Cool to' which was confusing a little, but at least status was always green not blue or orange.)

I know that HomeKit has a Fan service... Is it possible to have both a HeaterCooler thermostat service and a separate Fan controller service for the same device? (In the config, the user could choose to do this or just ignore the fan service.) If the HeaterCooler control was AUTO, HEAT or COOL, the Fan service would automatically be OFF, or if the Fan service was turned on, the HeaterCooler service would then automatically display as off?

That would force every AC to be 2 tiles, but they would both correctly display what they are really doing... I don't know if this is possible, or if it is a lot of difficult work. Just thinking about loud. :)

Thanks again for all the effort you've been putting in!

**Comment by Elethom** [comment]
In version 0.5.0 and earlier, unknown mode was interpreted as cool. It was never correct since HomeKit only supports auto, heat, cool. It will be removed and replaced by a separate device.

**Comment by Elethom** [comment]
Implemented in 1.0.0 along with dry mode.

**Comment by keness521** [comment]
I'm getting the following error after installing. The fan controls seem to work, but the whole title in HomeKit shows as No Response and I can't seem to get past it.

[05/04/2021, 15:09:30] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by keness521** [comment]
Did some more testing. Everything related to the fan (and dry) seems to work, but the thermostat controls are not usable, and the HomeKit tile as a whole shows "No Response" (although if you go into it, you can use the fan, but not the thermostat).

![v1 0-1](https://user-images.githubusercontent.com/79359679/113617344-352c0b00-9624-11eb-9e9c-0c15464d28f2.jpg)
![v1 0-2](https://user-images.githubusercontent.com/79359679/113617346-352c0b00-9624-11eb-93c2-178bbf7366ba.jpg)

**Comment by Elethom** [comment]
That is the expected behaviour but it shouldn't leave the AC not responding.

**Comment by keness521** [comment]
I think the problem is there are a lot of "undefined" variables for some reason?

I'm getting that error once every second, for every air conditioner.

I was able to clear the 'Target Heater-Cooler State' undefined error by going into the GREE+ app and  turning on HEAT mode. The "Target Heater-Cooler State" error went way, but now it is a "Rotation Direction" undefined error instead.

When the plugin first starts up, does it do a full GET from the device to determine all the current defined settings? It looks like it does do that, but the errors seem to all be "undefined" related.

**Comment by keness521** [comment]
If I turn FAN back on in the tile (it was in HEAT), the continuous 'Target Heater-Cooler State' undefined error returns.

The thermostat immediately went to OFF when I turned the FAN on, but the error returned and it still shows as "No Response".

**Comment by Elethom** [comment]
Seems HomeKit checks status even when the device is off. I thought that was not necessary so I didn't return them to HomeKit. This should be fixed in 1.0.1.

**Comment by keness521** [comment]
Bingo, everything works perfect now. Thanks!
