### ISSUE TITLE
Description of Oscillation modes...

### ISSUE THREAD

**Issue by keness521** [Elethom/homebridge-gree-heatercooler-v2#16]
Loving v1.0.1... It is working great!

Was wondering if you could give a little more explanation of the oscillation and autoOscillation modes and how they work? I can't quite seem to wrap my head around it.

I think I've figured it out, though. Is this correct?

1) If Oscillation is ON in HomeKit, use 'oscillation: on' option value for horizontal and/or vertical oscillation.
     -- If 'default' then... per description in readme.
     -- If 'fallback' then (and only then?) use the option values defines for each mode in autoOscillation?
     -- Otherwise, use the option specified here, for ALL modes.
2) If Oscillation is OFF in HomeKit, use 'oscillation: off' option value for horizontal and/or vertical oscillation.
     -- If 'default' then... per description in readme.
     -- If 'fallback' then (and only then?) use the option values defines for each mode in autoOscillation?
     -- Otherwise, use the option specified here, for ALL modes.

So, autoOscillation is only used to define different options for each mode when the 'oscillation' mode is set to fallback?

Also, one small correction to the Readme and one small suggestion...

For the Readme, it says that clockwise means fan and counter-clockwise means dry, but it is actually the other way around. In reality, you have it programmed so that clockwise means dry and counter-clockwise means fan. Either way is fine, but the readme doesn't match the actual behavior.

For the oscillation defaults: Since hot air rises, you'd normally want it to blow low then naturally rise up, and for cool air which falls, you want to blow it high, and let it fall down. According to the Readme, the defaults are the opposite. Nothing wrong with that, but my guess is that the other way around would be more "natural" for the way warm and cool air work.

Thanks!

**Comment by Elethom** [comment]
1. That's basically it, except for one thing: `default` is Gree's definition for "do not swing". If you want to use the default configs set by me you can just leave them empty.
2. The arrow shown in Home app actually means "switch to that direction" instead of currently rotating in that direction. That's a bit confusing but you can see the definition here is not wrong: 
https://github.com/Elethom/homebridge-gree-heatercooler-v2/blob/master/dist/accessory.js#L325
```javascript
  set fan_mode(value) {
    const mode = (() => {
      switch (value) {
        case Characteristic.RotationDirection.COUNTER_CLOCKWISE:
          return commands.mode.value.dry;
        case Characteristic.RotationDirection.CLOCKWISE:
          return commands.mode.value.fan;
      }
    })();
    if (mode === this.device.status[commands.mode.code]) return;
    
    this._setMode(mode);
  }
```
3. That's a typo in the readme. It's actually working the way you want. Sorry. 😆

**Comment by Elethom** [comment]
Readme is updated.
