### ISSUE TITLE
accessory parameter must be unique ？

### ISSUE THREAD

**Issue by charli117** [Elethom/homebridge-gree-heatercooler-v2#17]
Hi：
     If there are two same air conditioning that how configuration？
     
![image](https://user-images.githubusercontent.com/24435100/118443309-52bdbb80-b71e-11eb-846f-89d240325f46.png)

**Comment by Elethom** [comment]
Sorry but I couldn’t understand your issue. Please paste full config here and state your issue clearly.

**Comment by Elethom** [comment]
Closed for no update is given.
