### ISSUE TITLE
Problem with Yeelight module.

### ISSUE THREAD

**Issue by quartist** [Elethom/homebridge-gree-heatercooler-v2#19]
Hello,

I found a problem after migrate homebridge-gree-heatercooler to homebridge-gree-heatercooler-v2 with homebridge-yeelight-wifi module.
After migration to homebridge-gree-heatercooler-v2 all automation witch use Yeelight lamp are stop working - lamps stops work in automation. After rollback config and change heatercooler-v2 to heatercooler module, all automation starts working correctly (without any manually edition of automation tasks).

**Comment by Elethom** [comment]
Hi, please add some details to this issue. For example, do basic functions work? And please paste your config and logs here.

**Comment by kongkx** [comment]
I came into the same situation. I config gree-heatercooler as a child bridge, and now  `homebridge-yeelight-wifi` and `homebridge-gree-heatercooler-v2` can work together.

```
{
    "accessory": "GreeHeaterCooler",
    "name": "GreeHeaterCooler",
    "address": "xxx.xxx.xxx.xxx",
    "xFan": true,
    "lightControl": true,
    "fakeSensor": false,
    "sensorOffset": 0,
    "updateInterval": 1000,
    "retryInterval": 5000,
    "_bridge": {
        "username": "0E:4E:E9:C4:C9:A7",
        "port": 42534
    }
}
```

**Comment by quartist** [comment]
> I came into the same situation. I config gree-heatercooler as a child bridge, and now `homebridge-yeelight-wifi` and `homebridge-gree-heatercooler-v2` can work together.
> 
> ```
> {
>     "accessory": "GreeHeaterCooler",
>     "name": "GreeHeaterCooler",
>     "address": "xxx.xxx.xxx.xxx",
>     "xFan": true,
>     "lightControl": true,
>     "fakeSensor": false,
>     "sensorOffset": 0,
>     "updateInterval": 1000,
>     "retryInterval": 5000,
>     "_bridge": {
>         "username": "0E:4E:E9:C4:C9:A7",
>         "port": 42534
>     }
> }
> ```

Yes! That's solved the problem. Thanks!
