### ISSUE TITLE
Tempsensor is in Fahrenheit but target temp in Celsius

### ISSUE THREAD

**Issue by zsdudics** [Elethom/homebridge-gree-heatercooler-v2#22]
Hi! 

I have a problem with my Gree GWH18UC using Homebridge plugin version 1.0.2. In Home app the temp sensor is showing the temperature in Fahrenheit while the target temperature is in Celsius it's working normal.
The AC icon shows 78, but when I want to set the target temp it's already in Celsius and can be set between 16-30 (or what is defined in the json). In the Home app under settings of the accessory the Celsius is set as default.

I have another temp sensor in this room showing 25.5 Celsius now which is about 78 F.

**Comment by Elethom** [comment]
Sorry but I'm not sure what you mean.

The switch only decides the unit displayed on your AC's LED. The unit displayed in your Home app depends on your iOS settings.

**Comment by zsdudics** [comment]
Opening the Home app the icon of Gree AC shows 78, when I tap on it I can select the target temperatute already in Celsius. I have other thermostats in Homekit (Tado or Daikin AC via homebridge too), they are working totally fine: temperature sensor and targets are all in Celsius. For Gree it's mixed somehow.

**Comment by Elethom** [comment]
That’s weird. So your actual temperature is 25.5C (78F) right?

**Comment by Elethom** [comment]
The display unit is decided by your Home app. All temperature values used in the plugin are in Celsius. 

Sorry I cannot debug the plugin due to lack of a testing device (I no longer have a Gree AC). But you can try:
* checking if the issue persists on another phone
* checking if the issue appears on earlier versions of the plugin

Thank you for your feedback!

**Comment by zsdudics** [comment]
Hello!

The 78 is already visible in the Homebridge when I check the accessory details:

![image](https://user-images.githubusercontent.com/2420227/126448831-d1ca4249-b7e1-4d68-b543-1084b50c8f3a.png)

My config:

{
            "accessory": "GreeHeaterCooler",
            "name": "Living Room AC",
            "address": "192.168.68.149",
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "oscillation": {
                "on": {
                    "horizontal": "full",
                    "vertical": "fallback"
                },
                "off": {
                    "horizontal": "default",
                    "vertical": "fallback"
                }
            },
            "autoOscillation": {
                "auto": {
                    "horizontal": "default",
                    "vertical": "default"
                },
                "cool": {
                    "horizontal": "default",
                    "vertical": "fixedHighest"
                },
                "heat": {
                    "horizontal": "default",
                    "vertical": "fixedLowest"
                },
                "fan": {
                    "horizontal": "default",
                    "vertical": "full"
                },
                "dry": {
                    "horizontal": "default",
                    "vertical": "full"
                }
            },
            "xFan": true,
            "lightControl": false,
            "fakeSensor": false,
            "sensorOffset": 40,
            "updateInterval": 1000,
            "retryInterval": 5000
        }

**Comment by zsdudics** [comment]
One more thing: right now in the same room the temperature is only 24 Celsius, which is definitely less than 78 F, but the Gree is still showing 78. Can be that the value is just a constanst value and has nothing to do with Fahrenheit vs Celsius?

**Comment by Elethom** [comment]
I'm not sure. Please turn on debug mode for Homebridge and post some logs.

**Comment by zsdudics** [comment]
Hi!

Here you can find debug logs about the Gree AC, while I turned it on in cooling mode then turned it off.

[LivingRoomAC_debugLOG.txt](https://github.com/Elethom/homebridge-gree-heatercooler-v2/files/6856437/LivingRoomAC_debugLOG.txt)

**Comment by zsdudics** [comment]
When I change the offset to 0, I get these lines, and it shows 100 in the Home app too.

[7/21/2021, 4:22:01 PM] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 118 exceeded maximum of 100. See https://git.io/JtMGR for more info.

**Comment by Elethom** [comment]
The sensor always returns 118 from what I see. That’s probably a malfunction on your AC side.

**Comment by zsdudics** [comment]
The "Gree+" application or the led on the AC unit can show the correct values therefore I guess the sensor itself is not malfunctioning. Is there any way to query the temperature data via other method maybe?

**Comment by Elethom** [comment]
It did pass `"TemSen":118` back on every update. What number does your app show?

**Comment by Elethom** [comment]
According to https://github.com/tomikaa87/gree-remote#getting-the-current-temperature-reading-from-the-internal-sensor
There is no other known way to get sensor data.

**Comment by zsdudics** [comment]
> It did pass `"TemSen":118` back on every update. What number does your app show?

So, in the "Gree+" application there is no way to see the current temperature - or I was not able to find it, only the target temp is visible. However the LED of the unit itself is able to show the temperature of: current temp, target temp and outside temp. This can be checked using the remote controller. If you say there is no other way to query the temperature then it's an issue you cannot solve for me and I have to live with it. :(

**Comment by Elethom** [comment]
If their own app cannot get the temperature it’s probably not supported. Sorry but I don’t think I can help with that.
