### ISSUE TITLE
Device not found at undefined:7000, retrying...

### ISSUE THREAD

**Issue by imjyang** [Elethom/homebridge-gree-heatercooler-v2#23]
首先感谢作者分享的插件

[05/08/2021, 23:35:04] [GreeHeaterCooler] Device not found at undefined:7000, retrying...

格力+的app上可以控制空调，但是Homebridge报上面的错误，请问有什么建议吗？

**Comment by Elethom** [comment]
`address`: Local IP address of the AC unit.
