### ISSUE TITLE
Space Temperature display reading 131

### ISSUE THREAD

**Issue by mattcontrols** [Elethom/homebridge-gree-heatercooler-v2#4]
I have “fake sensor” set to false as my unit has a built-in space temperature sensor, but the space temperature icon is showing 131, when in reality it is around 60° F.

![3C0D266D-7B68-4104-8958-297A728FD2FC](https://user-images.githubusercontent.com/37245719/106209555-17e94500-617a-11eb-9b34-f8bb33885d3f.jpeg)
![0A7551A1-D50A-4E7A-822C-A745F3BD72F9](https://user-images.githubusercontent.com/37245719/106209563-19b30880-617a-11eb-9547-b25c46265834.jpeg)

**Comment by Elethom** [comment]
This should be because of Gree's mechanism to avoid negative values. Supported in 0.3.0. Setting `sensorOffset` to 40 should solve this issue.
