### ISSUE TITLE
Some ACs do not respond to scan

### ISSUE THREAD

**Issue by vanagnostos** [Elethom/homebridge-gree-heatercooler-v2#7]
Hi there, 

I have few Gree's (GWH12ACC-K6DNA1D/I, GWH09ACC-K6DNA1D/I) which only respond to scan while in setup mode and this breaks this otherwise very nice plugin. I've seen other people complainining of same problem, maybe it happens with newer or just specific models.  

However, they allow direct binding (you only need to know the mac address) and everything else works perfectly fine. 

I've made very simple change in your code to allow setting mac address in the config and trying bind if scan fails and there is mac configured. Would you be interested to see it? 

Thanks!

**Comment by Elethom** [comment]
Sure! Please fire a patch or pull request.
